kind: pipeline
name: default
type: kubernetes
services:
  - name: localhost
    image: skinnyjames/grits-gitea-fixture:latest
    network_mode: bridge
steps:
  - name: tests
    image: skinnyjames/crystal-libgit2
    environment:
      CI: true
    commands:
      - crystal spec
    network_mode: bridge