kind: pipeline
name: default
type: kubernetes
services:
  - name: gitea
    image: skinnyjames/grits-gitea-fixture:latest
    network_mode: bridge
steps:
  - name: tests
    image: skinnyjames/crystal-libgit2
    environment:
      CI: true
      GITEA_PRIVATE_KEY:
        from_secret: gitea_secret_key
      GITEA_PUBLIC_KEY:
        from_secret: gitea_public_key
      GITEA_ACCESS_TOKEN:
        from_secret: gitea_access_token
    commands:
      - chmod 700 spec/helpers/gitea/gitea
      - eval $(ssh-agent)
      - crystal spec
    network_mode: bridge