before_script:
  - shards install

cache:
  paths:
    - lib/

spec:
  stage: test
  services:
    - alias: gitea
      name: skinnyjames/grits-gitea-fixture:latest
  image: "skinnyjames/crystal-libgit2"
  variables:
    CI: 'true'
  script:
    - chmod 700 spec/helpers/gitea/gitea
    - eval $(ssh-agent)
    - crystal spec

pages:
  image: crystallang/crystal:latest
  needs:
    - spec
  script:
    - apt-get update -y
    - apt-get install -y software-properties-common
    - add-apt-repository ppa:deadsnakes/ppa
    - apt-get install -y python3.8 python3.8-venv python3.10-venv
    - make build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
